[package]
name = "mandelbrot-O3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
generic-array = "0.14.5"
numeric-array = "0.5.2"
num-traits = "0.2.14"
